# Generated by Django 6.0.5 on 2026-05-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_author_auditlog_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='reason',
        ),
        migrations.AddField(
            model_name='story',
            name='storyteller_photo',
            field=models.ImageField(blank=True, help_text='Optional photo of the person telling the story', null=True, upload_to='storyteller_photos/'),
        ),
        migrations.AddField(
            model_name='verification',
            name='comments',
            field=models.TextField(default='Initial entry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verification',
            name='proof_url',
            field=models.URLField(default='Initial entry'),
            preserve_default=False,
        ),
    ]
